POST http://localhost:3000/trades
Content-Type: application/json

{
    "schemaVersion": "1.0.0",
    "pairs": [
        {
            "chainId": "injective",
            "dexId": "dojoswap",
            "url": "https://dexscreener.com/injective/inj17ufy5gqw33t0prwhkwa6ensv0jpj3xfvylgx8j",
            "pairAddress": "inj17ufy5gqw33t0prwhkwa6ensv0jpj3xfvylgx8j",
            "baseToken": {
                "address": "inj19dtllzcquads0hu3ykda9m58llupksqwekkfnw",
                "name": "Baby DOJO Token",
                "symbol": "babyDOJO"
            },
            "quoteToken": {
                "address": "inj1zdj9kqnknztl2xclm5ssv25yre09f8908d4923",
                "name": "Dojo Token",
                "symbol": "DOJO"
            },
            "priceNative": "0.006624",
            "priceUsd": "0.004128",
            "txns": {
                "m5": {
                    "buys": 0,
                    "sells": 4
                },
                "h1": {
                    "buys": 1,
                    "sells": 21
                },
                "h6": {
                    "buys": 5,
                    "sells": 156
                },
                "h24": {
                    "buys": 8,
                    "sells": 608
                }
            },
            "volume": {
                "h24": 290436.72,
                "h6": 86601.67,
                "h1": 21370.42,
                "m5": 7739.51
            },
            "priceChange": {
                "m5": -4.2,
                "h1": -10.04,
                "h6": -2.28,
                "h24": -4.25
            },
            "liquidity": {
                "usd": 829050.77,
                "base": 98672321,
                "quote": 676716
            },
            "pairCreatedAt": 1710685033000,
            "info": {
                "imageUrl": "https://dd.dexscreener.com/ds-data/tokens/injective/inj19dtllzcquads0hu3ykda9m58llupksqwekkfnw.png",
                "websites": [
                    {
                        "label": "Website",
                        "url": "https://baby.dojo.trading/"
                    },
                    {
                        "label": "Docs",
                        "url": "https://docs.dojo.trading/"
                    },
                    {
                        "label": "Main Site",
                        "url": "https://dojo.trading/"
                    }
                ],
                "socials": [
                    {
                        "type": "twitter",
                        "url": "https://twitter.com/Dojo_Swap"
                    },
                    {
                        "type": "telegram",
                        "url": "https://t.me/dojo_swap"
                    }
                ]
            }
        },
        {
            "chainId": "injective",
            "dexId": "dojoswap",
            "url": "https://dexscreener.com/injective/inj19ucgk3rghfwu9an5vdl3kxf02h8cguk50042ff",
            "pairAddress": "inj19ucgk3rghfwu9an5vdl3kxf02h8cguk50042ff",
            "baseToken": {
                "address": "inj19dtllzcquads0hu3ykda9m58llupksqwekkfnw",
                "name": "Baby DOJO Token",
                "symbol": "babyDOJO"
            },
            "quoteToken": {
                "address": "inj",
                "name": "Injective",
                "symbol": "INJ"
            },
            "priceNative": "0.0001300",
            "priceUsd": "0.004829",
            "txns": {
                "m5": {
                    "buys": 0,
                    "sells": 0
                },
                "h1": {
                    "buys": 0,
                    "sells": 2
                },
                "h6": {
                    "buys": 0,
                    "sells": 8
                },
                "h24": {
                    "buys": 0,
                    "sells": 36
                }
            },
            "volume": {
                "h24": 1024.48,
                "h6": 238.99,
                "h1": 48.03,
                "m5": 0
            },
            "priceChange": {
                "m5": 0,
                "h1": 1.42,
                "h6": 34.62,
                "h24": 6.73
            },
            "liquidity": {
                "usd": 599.28,
                "base": 65538,
                "quote": 7.6163
            },
            "pairCreatedAt": 1710163106000,
            "info": {
                "imageUrl": "https://dd.dexscreener.com/ds-data/tokens/injective/inj19dtllzcquads0hu3ykda9m58llupksqwekkfnw.png",
                "websites": [
                    {
                        "label": "Website",
                        "url": "https://baby.dojo.trading/"
                    },
                    {
                        "label": "Docs",
                        "url": "https://docs.dojo.trading/"
                    },
                    {
                        "label": "Main Site",
                        "url": "https://dojo.trading/"
                    }
                ],
                "socials": [
                    {
                        "type": "twitter",
                        "url": "https://twitter.com/Dojo_Swap"
                    },
                    {
                        "type": "telegram",
                        "url": "https://t.me/dojo_swap"
                    }
                ]
            }
        }
    ]
}
###
GET http://localhost:3000/api/trades

